version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      - git fetch --unshallow || true

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf
  - htmlzip

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - dev
